### ISSUE TITLE
Visualization from demo video

### ISSUE THREAD

**Issue by tonywong-1115** [chenyilun95/DSGN2#16]
hello, is the code of visualization part from demo video also availiable for public? thanks!

**Comment by chenyilun95** [comment]
Hi, the result is generated by inferencing the raw data sequence of KITTI. You might visualize the result of each frame via some tools like https://github.com/kuixu/kitti_object_vis.

**Comment by tonywong-1115** [comment]
Thanks for ur advice, ill check it later.
