### ISSUE TITLE
RuntimeError: NCCL error 

### ISSUE THREAD

**Issue by tonywong-1115** [chenyilun95/DSGN2#17]
Hello, I met the NCCL error when running the test.py file. Could u pls help me about this? thanks.

my setup: Torch1.71 + CUDA11.3 ubuntu20.04
Package                       Version       Editable project location
----------------------------- ------------- --------------------------------------------
actionlib                     1.14.0
addict                        2.4.0
angles                        1.9.13
ansi2html                     1.8.0
asttokens                     2.2.1
attrs                         23.1.0
backcall                      0.2.0
bondpy                        1.8.6
camera-calibration            1.17.0
camera-calibration-parsers    1.12.0
catkin                        0.8.10
certifi                       2023.5.7
charset-normalizer            3.1.0
click                         8.1.4
colorama                      0.4.6
comm                          0.1.3
ConfigArgParse                1.5.5
configparser                  5.3.0
contourpy                     1.1.0
controller-manager            0.19.6
controller-manager-msgs       0.19.6
cv-bridge                     1.16.2
cycler                        0.11.0
Cython                        0.29.36
dash                          2.11.1
dash-core-components          2.0.0
dash-html-components          2.0.0
dash-table                    5.0.0
debugpy                       1.6.7
decorator                     5.1.1
diagnostic-analysis           1.11.0
diagnostic-common-diagnostics 1.11.0
diagnostic-updater            1.11.0
dynamic-reconfigure           1.7.3
easydict                      1.10
executing                     1.2.0
fastjsonschema                2.17.1
Flask                         2.2.5
fonttools                     4.40.0
gazebo_plugins                2.9.2
gazebo_ros                    2.9.2
gencpp                        0.7.0
geneus                        3.0.0
genlisp                       0.4.18
genmsg                        0.6.0
gennodejs                     2.0.2
genpy                         0.6.15
idna                          3.4
image-geometry                1.16.2
imageio                       2.31.1
importlib-metadata            6.8.0
importlib-resources           5.13.0
interactive-markers           1.12.0
ipykernel                     6.24.0
ipython                       8.12.2
ipywidgets                    8.0.7
itsdangerous                  2.1.2
jedi                          0.18.2
Jinja2                        3.1.2
joblib                        1.3.1
joint-state-publisher         1.15.1
joint-state-publisher-gui     1.15.1
jsonschema                    4.18.0
jsonschema-specifications     2023.6.1
jupyter_client                8.3.0
jupyter_core                  5.3.1
jupyterlab-widgets            3.0.8
kiwisolver                    1.4.4
laser_geometry                1.6.7
lazy_loader                   0.3
llvmlite                      0.40.1
Markdown                      3.4.3
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.7.2
matplotlib-inline             0.1.6
mdurl                         0.1.2
message-filters               1.16.0
mmcv-full                     1.4.0
mmdet                         2.22.0        /home/toni/GitRepo/DSGN2/mmdetection-v2.22.0
model-index                   0.1.11
nbformat                      5.7.0
nest-asyncio                  1.5.6
networkx                      3.1
numba                         0.57.1
numpy                         1.24.4
open3d                        0.17.0
opencv-python                 4.8.0.74
opendatalab                   0.0.9
openmim                       0.3.9
ordered-set                   4.1.0
packaging                     23.1
pandas                        2.0.3
parso                         0.8.3
pcdet                         0.1.0+a904f61 /home/toni/GitRepo/DSGN2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        10.0.0
pip                           23.1.2
pkgutil_resolve_name          1.3.10
platformdirs                  3.8.1
plotly                        5.15.0
prompt-toolkit                3.0.39
protobuf                      4.23.4
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycocotools                   2.0.2
pycryptodome                  3.18.0
Pygments                      2.15.1
pyparsing                     3.0.9
pyquaternion                  0.9.9
python-dateutil               2.8.2
python-qt-binding             0.4.4
pytz                          2023.3
PyWavelets                    1.4.1
PyYAML                        6.0
pyzmq                         25.1.0
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
referencing                   0.29.1
requests                      2.31.0
resource_retriever            1.12.7
retrying                      1.3.4
rich                          13.4.2
rosbag                        1.16.0
rosboost-cfg                  1.15.8
rosclean                      1.15.8
roscreate                     1.15.8
rosgraph                      1.16.0
roslaunch                     1.16.0
roslib                        1.15.8
roslint                       0.12.0
roslz4                        1.16.0
rosmake                       1.15.8
rosmaster                     1.16.0
rosmsg                        1.16.0
rosnode                       1.16.0
rosparam                      1.16.0
rospy                         1.16.0
rosservice                    1.16.0
rostest                       1.16.0
rostopic                      1.16.0
rosunit                       1.15.8
roswtf                        1.16.0
rpds-py                       0.8.10
rqt_action                    0.4.9
rqt_bag                       0.5.1
rqt_bag_plugins               0.5.1
rqt_console                   0.4.11
rqt_dep                       0.4.12
rqt_graph                     0.4.14
rqt_gui                       0.5.3
rqt_gui_py                    0.5.3
rqt-image-view                0.4.17
rqt_launch                    0.4.9
rqt_logger_level              0.4.11
rqt-moveit                    0.5.10
rqt_msg                       0.4.10
rqt_nav_view                  0.5.7
rqt_plot                      0.4.13
rqt_pose_view                 0.5.11
rqt_publisher                 0.4.10
rqt_py_common                 0.5.3
rqt_py_console                0.4.10
rqt-reconfigure               0.5.5
rqt-robot-dashboard           0.5.8
rqt-robot-monitor             0.5.14
rqt_robot_steering            0.5.12
rqt_runtime_monitor           0.5.9
rqt-rviz                      0.7.0
rqt_service_caller            0.4.10
rqt_shell                     0.4.11
rqt_srv                       0.4.9
rqt_tf_tree                   0.6.3
rqt_top                       0.4.10
rqt_topic                     0.4.13
rqt_web                       0.4.10
rviz                          1.14.20
scikit-image                  0.21.0
scikit-learn                  1.3.0
scipy                         1.10.1
sensor-msgs                   1.13.1
setuptools                    67.8.0
six                           1.16.0
smach                         2.5.1
smach-ros                     2.5.1
smclib                        1.8.6
spconv                        1.2.1
stack-data                    0.6.2
tabulate                      0.9.0
tenacity                      8.2.2
tensorboardX                  2.6.1
terminaltables                3.1.10
tf                            1.13.2
tf-conversions                1.13.2
tf2-geometry-msgs             0.7.6
tf2-kdl                       0.7.6
tf2-py                        0.7.6
tf2-ros                       0.7.6
threadpoolctl                 3.1.0
tifffile                      2023.7.10
tomli                         2.0.1
topic-tools                   1.16.0
torch                         1.7.1
torchvision                   0.8.2
tornado                       6.3.2
tqdm                          4.65.0
traitlets                     5.9.0
typing_extensions             4.7.1
tzdata                        2023.3
urllib3                       2.0.3
wcwidth                       0.2.6
Werkzeug                      2.2.3
wheel                         0.38.4
widgetsnbextension            4.0.8
xacro                         1.14.16
yapf                          0.40.1
zipp                          3.15.0

Log:

Traceback (most recent call last):
  File "tools/test.py", line 210, in <module>
    main()
  File "tools/test.py", line 197, in main
    test_set, test_loader, sampler = build_dataloader(
  File "/home/toni/GitRepo/DSGN2/pcdet/datasets/__init__.py", line 43, in build_dataloader
    dataset = __all__[dataset_cfg.DATASET](
  File "/home/toni/GitRepo/DSGN2/pcdet/datasets/kitti/stereo_kitti_dataset.py", line 40, in __init__
    self.include_kitti_data(self.mode)
  File "/home/toni/GitRepo/DSGN2/pcdet/datasets/kitti/stereo_kitti_dataset.py", line 56, in include_kitti_data
    assert len(self.sample_id_list) == len(self.kitti_infos)
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "tools/test.py", line 210, in <module>
    main()
  File "tools/test.py", line 147, in main
    total_gpus, cfg.LOCAL_RANK = getattr(common_utils, 'init_dist_%s' % args.launcher)(
  File "/home/toni/GitRepo/DSGN2/pcdet/utils/common_utils.py", line 246, in init_dist_pytorch
    dist.init_process_group(
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:94, invalid argument, NCCL version 2.7.8
Traceback (most recent call last):
  File "tools/test.py", line 210, in <module>
    main()
  File "tools/test.py", line 147, in main
    total_gpus, cfg.LOCAL_RANK = getattr(common_utils, 'init_dist_%s' % args.launcher)(
  File "/home/toni/GitRepo/DSGN2/pcdet/utils/common_utils.py", line 246, in init_dist_pytorch
    dist.init_process_group(
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:94, invalid argument, NCCL version 2.7.8
Traceback (most recent call last):
  File "tools/test.py", line 210, in <module>
    main()
  File "tools/test.py", line 147, in main
    total_gpus, cfg.LOCAL_RANK = getattr(common_utils, 'init_dist_%s' % args.launcher)(
  File "/home/toni/GitRepo/DSGN2/pcdet/utils/common_utils.py", line 246, in init_dist_pytorch
    dist.init_process_group(
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:94, invalid argument, NCCL version 2.7.8
Traceback (most recent call last):
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/toni/anaconda3/envs/dsgn/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/toni/anaconda3/envs/dsgn/bin/python', '-u', 'tools/test.py', '--local_rank=3', '--launcher', 'pytorch', '--workers', '2', '--save_to_file', '--cfg_file', './configs/stereo/kitti_models/dsgn2.yaml', '--exp_name', 'default', '--tcp_port', '12345', '--ckpt_id', '60']' returned non-zero exit status 1.

**Comment by chenyilun95** [comment]
You might need to avoid the mismatch of pytorch, cudatoolkit, driver version. https://docs.nvidia.com/deploy/cuda-compatibility/index.html

**Comment by tonywong-1115** [comment]
hello, thanks for ur reply! After recreating a virtual env i was enble to deal with the problem i met before, but now I encounter a new error:
Traceback (most recent call last):
  File "tools/test.py", line 210, in <module>
    main()
  File "tools/test.py", line 147, in main
    total_gpus, cfg.LOCAL_RANK = getattr(common_utils, 'init_dist_%s' % args.launcher)(
  File "/home/toni/DSGN2/pcdet/utils/common_utils.py", line 246, in init_dist_pytorch
    dist.init_process_group(
  File "/home/toni/anaconda3/envs/dsgn2/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/toni/anaconda3/envs/dsgn2/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe
Traceback (most recent call last):
  File "tools/test.py", line 210, in <module>
    main()
  File "tools/test.py", line 147, in main
    total_gpus, cfg.LOCAL_RANK = getattr(common_utils, 'init_dist_%s' % args.launcher)(
  File "/home/toni/DSGN2/pcdet/utils/common_utils.py", line 246, in init_dist_pytorch
    dist.init_process_group(
  File "/home/toni/anaconda3/envs/dsgn2/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/toni/anaconda3/envs/dsgn2/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: Broken pipe

Is this relevant to the data preparation step? because I havent downloaded the dataset from KITTI yet. Thanks

**Comment by tonywong-1115** [comment]
and I would like to ask a noob question, for example, if I want to use the pretrained model u provided to do inference on a stereo img pair, what should I do? Thx!

**Comment by chenyilun95** [comment]
Yes, it requires KITTI data preparation. You can simply download the KITTI using opendatalab. For inference on a stereo image pair, the simplest way is to modify the data loader and feed your image. 

You could try debugging with no distributed inference and no data worker like: python tools/test.py --cfg_file ./configs/stereo/kitti_models/dsgn2.yaml --workers 0 --ckpt_id xx.

**Comment by tonywong-1115** [comment]
Thanks for ur advice. And one more question, when running the test.py file, why we dont need to feed the pretrained pth file to it?

**Comment by chenyilun95** [comment]
The --ckpt_id option means the .pth file.
