### ISSUE TITLE
About coordinate transform from camera frustum space to 3d world

### ISSUE THREAD

**Issue by QitaoZhao** [chenyilun95/DSGN2#2]
Could you please explain what cu and cv mean in the formula? 
Besides, I'm curious about the derivation of this formula. I wonder if you could provide some references. 
Thanks for your nice work.
<img width="473" alt="Screen Shot 2022-06-22 at 20 09 40" src="https://user-images.githubusercontent.com/68940825/175025693-10a7b794-1e9d-4e2a-802f-220d60606974.png">

**Comment by chenyilun95** [comment]
They are the principal points of camera reference. More details are referred to camera projection geometry.
